### ISSUE TITLE
請更新一下 pureftpd 版本號

### ISSUE THREAD

**Issue by moewhale** [moeYuiYui/lnmp#2]
https://download.pureftpd.org/pure-ftpd/releases/
看 pureftpd 官網已經刪除了 1.0.49

lnmp/pureftpd.sh 中的下載鏈接中 刪除 /pub
lnmp/include/version.sh 更新一下新的版本號

**Comment by moeYuiYui** [comment]
可以先手动修改一下include/version.sh
Pureftpd_Ver='pure-ftpd-1.0.49'
改为Pureftpd_Ver='pure-ftpd-1.0.51'再重新安装
